#! /bin/bash
# mod: mount
# api: External
# txt: The `mount` module provides functions to ensure that specific
#      mountpoint is mounted.
# use: mount::present /mnt device=/dev/sda1 fstype=xfs

# fun: mount::exists [name=]<name> [opts]
# api: External
# txt: return true if specific device is mounted with passed options
# opt: device: the device to mount
# opt: fstype: the fstype of the device filesystem (default: auto)
mount::exists () {
  local name device fstype _mnt
  std::parse "$@"
  while read -r _ _ _mnt _ _ _; do
    [ "$_mnt" == "${name}" ] && return 0
  done < <(mount)
  return 1
}

mount::_create () {
  local name device fstype
  std::parse "$@"
  mount_opt="${fstype:+-t $fstype}"
  std::run mount "${mount_opt}" "${device}" "${name}"
}

mount::_destroy () {
  local name device fstype
  std::parse "$@"
  std::run umount "$name"
}

# fun: mount::present [name=]<name> [opts]
# api: External
# txt: ensure that specific device is mounted according with passed options.
# opt: device: the device to mount
# opt: fstype: the fstype of the device filesystem (default: auto)
mount::present () {
  if ! mount::exists "$@"; then
    if mount::_create "$@"; then
      res::created mount "$@"
    else
      err::trace "Unable to mount $*"
    fi
  else
    return 1
  fi
}

# fun: mount::absent [name=]<name>
# api: External
# txt: ensure that specific mount point is not mounted.
mount::absent () {
  if mount::exists "$@"; then
    if mount::_destroy "$@"; then
      res::deleted mount "$@"
    else
      err::trace "Unable to umont $*"
    fi
  else
    return 1
  fi
}
