#! /bin/bash
# mod: sudo
# txt: The `sudo` module provides functions to grant or deny permissions
#      to specific users.
# env: SUDOERS_DIR: the path where sudoers file exists, usually
#      `/etc/sudoers.d`.
# use: # ensure taht user someuser has ALL permissions
#      sudo::user::present someuser grant=ALL
# use: # ensure that group somegroup does not have ALL permissiones
#      sudo::group::absent somegroup grant=ALL

SUDOERS_DIR=/etc/sudoers.d

# private sudo::sytax <file>
sudo::_syntax () {
  std::mute visudo -cf "$1"
}

# fun: sudo::user::exists [name=]<username> grant=<permissions>
# api: External
# txt: return true if user has specific permissions
# opt: name: the username to check permissions
# opt: grant: the permissions to granted to the user.
sudo::user::exists () {
  local name grant
  std::parse "$@"
  [[ "$grant" ]] ||
      err::trace "The grant parameter is mandatory in sudo::user::exists"
  std::mute grep "^$name $grant$" "${SUDOERS_DIR}/20_user_$name"
}

# private sudo::user::_create <username> <sudoline>
sudo::user::_create () {
  if ! ${PRETEND:-false}; then
    echo "$1 $2" >> "${SUDOERS_DIR}/20_user_$1"
    if ! sudo::_syntax "${SUDOERS_DIR}/20_user_$1"; then
      rm -f "${SUDOERS_DIR}/20_user_$1"
      err::trace "Invalid syntax in sudoers file: '$2'"
    fi
  fi
}

# private sudo::user::_destroy <username> <sudoline>
sudo::user::_destroy () {
  if ! ${PRETEND:-false}; then
    local data; data="$(grep -v "^$1 $2$" "${SUDOERS_DIR}/20_user_$1")"
    echo "$data" > "${SUDOERS_DIR}/20_user_$1"
    if ! sudo::_syntax "${SUDOERS_DIR}/20_user_$1"; then
      rm -f "${SUDOERS_DIR}/20_user_$1"
      err::trace "Invalid syntax in sudoers file: '$2'"
    fi
  fi
}

# fun: sudo::user::present [name=]<username> grant=[permissions]
# api: External
# txt: ensure that specific user has permissions passed as argument, or if
#      not permissions defined grant root permissions.
# opt: name: the username to give permissions
# opt: grant: the permissions to granted to the user (by default ALL
#      NOPASSWD)
sudo::user::present () {
  local name grant
  std::parse "$@"
  grant="${grant:-ALL=(ALL) NOPASSWD: ALL}"

  if ! sudo::user::exists "$name" "grant=$grant"; then
    if sudo::user::_create "$name" "${grant}"; then
      res::created sudo "user=$name" "grant=${grant}"
    else
      err::trace "Unable to create sudo permissions for user $1 ('$grant')"
    fi
  else
    return 1
  fi
}

# fun: sudo::user::absent [name=]<username> grant=[permissions]
# api: External
# txt: ensure that the specific permission for the specific username is not
#      granted.
# opt: name: the username to give permissions
# opt: grant: the permissions to granted to the user
sudo::user::absent () {
  local name grant
  std::parse "$@"
  local grant="${grant:-ALL=(ALL) NOPASSWD: ALL}"

  if sudo::user::exists "$1" "grant=$grant"; then
    if sudo::user::_destroy "$1" "${grant}"; then
      res::deleted sudo "user=$name" "grant=$grant"
    else
      err::trace "Unable to destroy sudo permissions for user $name ('$grant')"
    fi
  else
    return 1
  fi
}

# fun: sudo::group::exists [name=]<username> grant=<sudoline>
# api: External
# txt: return true if group has configured the specific sudoline.
# opt: name: the username to give permissions
# opt: grant: the permissions to granted to the user
sudo::group::exists () {
  local name grant
  std::parse "$@"
  std::mute grep "^%$name $grant$" "${SUDOERS_DIR}/20_group_$name"
}

# private sudo::group::_create <groupname> <sudoline>
sudo::group::_create () {
  if ! ${PRETEND:-false}; then
    echo "%$1 $2" >> "${SUDOERS_DIR}/20_group_$1"
    if ! sudo::_syntax "${SUDOERS_DIR}/20_group_$1"; then
      rm -f "${SUDOERS_DIR}/20_group_$1"
      err::trace "Invalid syntax in sudoers file: '$2'"
    fi
  fi
}

# private sudo::group::_destroy <groupname> <sudoline>
sudo::group::_destroy () {
  if ! ${PRETEND:-false}; then
    local data; data="$(grep -v "^%$1 $2$" "${SUDOERS_DIR}/20_group_$1")"
    echo "$data" > "${SUDOERS_DIR}/20_group_$1"
    if ! sudo::_syntax "${SUDOERS_DIR}/20_group_$1"; then
      rm -f "${SUDOERS_DIR}/20_group_$1"
      err::trace "Invalid syntax in sudoers file: '$2'"
    fi
  fi
}

# fun: sudo::group::present [name=]<groupname> [grant=permissions]
# api: External
# txt: ensure that specific group has permissions passed as argument, or if
#      not permissions defined grant root permissions.
# opt: name: the username to give permissions
# opt: grant: the permissions to granted to the user (by default ALL
#      NOPASSWD)
sudo::group::present () {
  local name grant
  std::parse "$@"
  grant="${grant:-ALL=(ALL) NOPASSWD: ALL}"

  if ! sudo::group::exists "$name" "grant=$grant"; then
    if sudo::group::_create "$name" "${grant}"; then
      res::created sudo "group=$name" "grant=${grant}"
    else
      err::trace "Unable to create sudo permissions for group $name ('$grant')"
    fi
  else
    return 1
  fi
}

# fun: sudo::group::absent [name=]<groupname> [grant=permissions]
# api: External
# txt: ensure that the specific permission for the specific groupname is not
#      granted.
# opt: name: the username to give permissions
# opt: grant: the permissions to granted to the user (by default ALL
#      NOPASSWD)
sudo::group::absent () {
  local name grant
  std::parse "$@"
  grant="${grant:-ALL=(ALL) NOPASSWD: ALL}"

  if sudo::group::exists "$name" "grant=$grant"; then
    if sudo::group::destroy "$name" "${grant}"; then
      res::deleted sudo "group=$name" "grant=${grant}"
    else
      err::trace "Unable to destroy sudo permissions for group $name ('$grant')"
    fi
  else
    return 1
  fi
}
