#! /bin/bash
# mod: context
# api: Internal
# txt: This internal module provides functionality to run different context
#      in paralell.

alias context=function
alias namespace=function

declare -A __context__task
# fun: context::task::enqueue <fun>
# api: Internal
# txt: enqueue a task to be done when context finished.
context::task::enqueue () {
  if ! std::strin "${__context__task["${CONTEXT}"]}" ",$1,"; then
    __context__task["${CONTEXT}"]+=",$1,"
  fi
}

# fun: context::task::apply <context>
# api: Internal
# txt: apply functions enqueued by context::task::enqueue.
context::task::apply () {
  task="${__context__task["${1}"]}"
  if [ "$task" ]; then
    export IFS=,
    for t in $task; do
      [ "$t" ] || continue
      eval "${t}" || err::trace "Unable to apply post-context task: $t ($CONTEXT)"
    done
  fi
}

# fun: context::execute <name>
# api: Internal
# txt: Execute a context named as name.
# env: CONTEXT: contains the context name, and this variable will be
#      propagated to other functions in the same context.
context::execute () {
  export CONTEXT="$1" && $1 && context::task::apply "$1"
}

# fun: context::run
# api: Internal
# txt: run all context in paralell.
declare -a context__run__pids=()
context::run () {
  local tim cctx=0

  tim="$(std::timestamp)"
  # shellcheck disable=SC2015
  [ "$POTION_COMPILED" ] && local kind="compiled" || local kind="in-line"
  while read -r _ _ context; do
    ((cctx++))
  done < <(declare -F | grep '^declare -f @')

  out::user "found ${cctx} contexts"
  # shellcheck disable=SC2015
  ${PRETEND:-false} &&
    out::info "Starting $kind potion execution (pretending)" ||
    out::info "Starting $kind potion execution"

  while read -r _ _ context; do
    context::execute "$context" &
    if ${ONETHREAD:-false}; then
      wait $!
    else
      context__run__pids+=( "$!" )
    fi
  done < <(declare -F | grep '^declare -f @')
  if ! ${ONETHREAD:-false}; then
    [[ ${#context__run__pids[@]} -gt 0 ]] && 
      wait "${context__run__pids[@]}"
  fi
  context::task::apply "main"
  tim="$(( $(std::timestamp) - tim ))"
  out::info "Finished potion exection in ${tim} seconds."
}
