#! /bin/bash
# mod: dir
# txt: The ``dir`` module provides functions to ensure that specified
#      directory is created or destroyed.

# fun: dir::exists <fname>
# txt: return true if dir exists, or none otherwise
dir::exists () {
  [ -d "$1" ]
}

# fun: dir::create <dname> [owner:group] [chmod]
# txt: create dir passed as argument with properly owner and permissions.
# env: DIR_ARTIFACT: the directory from artifact to be copied on
dir::create () {
  mkdir -p "$1" &&
    chown "${2:-0:0}" "$1" &&
    chmod "${3:-755}" "$1"
}

# fun: dir::destroy <dname>
# txt: remove the dirname passed as argument
dir::destroy () {
  rm -rf "$1"
}

# fun: dir::present <dname> [owner:group] [chmod]
dir::present () {
  if ! dir::exists "$1"; then
    dir::create "$@" &&
      out::info "created dir: $1" ||
      err::trace "Unable to create dir: $1"
  fi
}


# fun: dir::absent <fname>
# txt: ensure that dir passed as argument does not exist.
dir::absent () {
  if dir::exists "$1"; then
    dir::destroy "$1" &&
      out::info "destroyed dir: $1" ||
      err::trace "Unable to destroy dir: $1"
  fi
}
