#! /bin/bash

# fun: host::exists <hostname>
# txt: return true if the FQDN of the node is equal to specified one.
host::exists () {
  local host="$(hostname -f 2>/dev/null)"
  [ "$host" == "$1" ]
}

# fun: host::create <hostname>
# txt: set the hostname of the node
host::create () {
  echo "${1%%.*}" > /etc/hostname
  echo "127.0.1.1 $1 ${1%%.*}" > /etc/hosts
  hostname "${1%%.*}"
}

# fun: host::destroy <hostname>
# txt: unset the hostname of the node
host::destroy () {
  local hosts="$(grep -v "^127.0.1.1 $1 ${1%%.*}" /etc/hosts)"

  echo > /etc/hostname
  echo "$hosts" > /etc/hosts
  hostname ''
}

# fun: host::present <hostname>
# txt: ensure than the node has the specified hostname.
host::present () {
  if ! host::exists "$1"; then
    host::create "$1" &&
      out::info "created host: $1" ||
      err::trace "Unable to create host to: $1"
  fi
}

# fun: host::ansent <hostname>
# txt: ensure than the node has not the specified hostname.
host::absent () {
  if host::exists "$1"; then
    host::destroy "$1" &&
      out::info "destroyed host: $1" ||
      err::trace "Unable to destroy host: $1"
  fi
}
