#! /bin/bash

# fun: link::exists <link> <source>
# txt: returnt true if the specified link exists and point to source.
link::exists () {
  [ -L "$1" ] && [ "$(readlink "$1")" == "$2" ]
}

# fun: link::create <link> <source>
# txt: create a link pointing to source
link::create () {
  ln -sf "$1" "$2"
}

# fun: link::destroy <link> [source]
# txt: destroy the link passed as argument
link::destroy () {
  rm -f "$1"
}

# fun: link::present <link> <source>
# txt: ensure that the link exists and point to source.
link::present () {
  if ! link::exists "$@"; then
    link::create "$@" &&
      out::info "created link: $2 ($1)" ||
      err::trace "Unable to create link: $2 ($1)"
  fi
}

# fun: link::absent <link> <source>
# txt: ensure that the specified link does not exists or not point to
#      specified source.
link::absent () {
  if link::exists "$@"; then
    link::destroy "$@" &&
      out::info "destroyed link: $2 ($1)" ||
      err::trace "Unable to destroy link: $2 ($1)"
  fi
}

