#! /bin/bash
# mod: main
# txt: The ``main`` module contain the specified potion body.

VERSION="0.2.5"
CONTEXT="main"

# fun: main::init
# txt: print nice potion logo and some custom messages at the beginning.
main::init () {
  out::user ""
  out::user "${COLOR_USER}                                   o${COLOR_NONE}"
  out::user "${COLOR_USER}                                     o${COLOR_NONE}"
  out::user "                                   ___"
  out::user "${COLOR_WARN} ____       _   _                  ${COLOR_NONE}| |"
  local m="${COLOR_WARN}|  _ \\ ___ | |_(_) ___  _ __       "
  m+="${COLOR_NONE}|${COLOR_USER}o${COLOR_NONE}|"
  out::user "$m"
  local m="${COLOR_WARN}| |_) / _ \| __| |/ _ \| '_ \\    ${COLOR_NONE}.'   '."
  out::user "$m"
  local m="${COLOR_WARN}|  __/ (_) | |_| | (_) | | | |  ${COLOR_NONE}/   "
  m+="${COLOR_USER}o${COLOR_NONE}   \\"
  out::user "$m"
  local m="${COLOR_WARN}|_|   \\___/ \\__|_|\___/|_| |_|  "
  m+="${COLOR_NONE}:${COLOR_USER}____o__${COLOR_NONE}:"
  out::user "$m"
  local m="                                '.${COLOR_USER}"
  m+="_____${COLOR_NONE}.'"
  out::user "$m"
  out::user "${COLOR_USER}version${COLOR_NONE} ${VERSION}" 
  out::user "detected hardware architecture: $(std::arch)"
  out::user "detected os family: $(os::family)"
  out::user "detected os provider: $(os::provider)"
}

# general options handlers
main::opt_debug () { set -x; return 1;}
main::opt_version () { out::info "Potion $VERSION"; exit 0;}
main::opt_quiet () { QUIET=true; return 1;}
main::opt_pretend () { PRETEND=true; return 1;}
main::opt_verbose () { VERBOSE=true; return 1;}

# create action
main::create::opt_artifacts () { main__create__artifacts="$1"; return 2;}
main::create::opt_compress () { main__create__compress=true; return 1;}
main::create::opt_output () { main__create__output="$1"; return 2;}
main::create::opt_secrets () { main__create__secrets="$1"; return 2;}

main::create () {
  local output=$'#! /bin/bash\nPOTION_COMPILED=true\n'
  ${QUIET:-false} || main::init
  out::info "output file: ${main__create__output:=./a.potion}"
  output+="$(<"$0")"$'\n'
  if [ "${main__create__artifacts}" ]; then
    [ -d "${main__create__artifacts}" ] ||
      err::trace "Artifacts directory does not exists or isn't a directory"

    [ -r "${main__create__artifacts}" ] ||
      err::trace "Unable to read artifacts directory"

    artifacts="$(cd "${main__create__artifacts}" &&
                 tar -c . | base64)"
    output+=$'\n'"$(artifact::build "${main__create__artifacts}")"$'\n'

    out::user "dumped artifacts from: ${main__create__artifacts}"
  fi
  if [ "${main__create__secrets}" ]; then
    output+=$'\n'"secret::load '${main__create__secrets}'"$'\n'
    out::user "set secret url to: ${main__create__secrets}"
  fi
  out::info "created core launcher"
  for template in "$@"; do
    [ -r "$template" ] ||
      err::trace "Unable to find template: $template"
    output+="$(<"$template")"$'\n'
    out::info "dumping template: $template"
  done
  output+=$'\ncontext::run\n'
  if ${main__create__compress:-false}; then
    local launcher="#!/bin/bash"$'\n'
    launcher+="POTION_PAYLOAD='$(echo "${output}" | gzip -9 | base64)'"$'\n'
    launcher+='exec bash < <(echo "$POTION_PAYLOAD" | base64 -d | gzip -d)'
    launcher+=$'\n'
    output="$launcher"
  fi
  echo "${output}" > "${main__create__output}"
}

# run action
main::run::opt_artifacts () { main__run__artifacts="$1"; return 2; }
main::run::opt_secrets () { main__run__secrets="$1"; return 2; }
main::run () {
  main::init "in-line"
  if [ "${main__run__artifacts}" ]; then
    [ -d "${main__run__artifacts}" ] ||
      err::trace "Artifacts directory does not exists or isn't a directory"

    [ -r "${main__run__artifacts}" ] ||
      err::trace "Unable to read artifacts directory"

    eval "$(artifact::build "${main__run__artifacts}")"
    out::user "dumped artifacts from: ${main__run__artifacts}"
  fi
  if [ "${main__run__secrets}" ]; then
    secret::load "${main__run__secrets}"
    out::user "loaded secrets from: ${main__run__secrets}"
  fi
  for src in "$@"; do
    curl::source "$src" || err::trace "Unable to load potion file(s): $src"
  done
  context::run
}

# fun: main [arguments]
# txt: function to create random errors and weird behaviour.
main () {
  # if this is a compiled potion, we don't need main
  ${POTION_COMPILED:-false} && main::init && return 0
  
  arg::opt MAIN -q --quiet   main::opt_quiet   'do not output messages'
  arg::opt MAIN -v --verbose main::opt_verbose 'enable verbose mode'
  arg::opt MAIN -d --debug   main::opt_debug   'enable debug mode'
  arg::opt MAIN -p --pretend main::opt_pretend 'do nothing, just pretending'
  arg::opt MAIN -V --version main::opt_version 'show program version number'

  arg::action create main::create 'create new potion from templates'
  arg::param create "infredients+" \
    'URL to the ingredient files to make the potion'
  arg::opt create -o: --output: main::create::opt_output \
    'set path to output potion filename'
  arg::opt create -a: --artifacts: main::create::opt_artifacts \
    'set path to artifacts directory'
  arg::opt create -c  --compress   main::create::opt_compress \
    'create compressed potion (require gzip)'
  arg::opt create -s:  --secrets:   main::create::opt_secrets \
    'set a secret file or URL to store passwords'
  
  arg::action run main::run 'run potion template'
  arg::param run "infredients+" \
    'path to the ingredient files to make the potion'
  arg::opt run -a: --artifacts: main::run::opt_artifacts \
    'set path to artifacts directory'
  arg::opt run -s:  --secrets:   main::run::opt_secrets \
    'set a secret file or URL to store passwords'

  arg::parse "$@"
}
shopt -s expand_aliases
