#! /bin/bash
# mod: meta
# api: Internal
# txt: This internal module provides information about metadata. The metadata
#      information is used internally by potion to store data discovered from
#      the system, like num of CPUs, the hostname, etc. This is an internal
#      module, so you might be not need to override metadata ever.

declare -A POTION_METADATA=()

# fun: meta::get <key>
# api: Internal
# txt: get the current value of key
meta::get ()
{
  echo "${POTION_METADATA["$1"]}"
}

# fun: meta::set <key> <value>
# api: Internal
# txt: add new value to the metadata
meta::set ()
{
  POTION_METADATA["$1"]="$2"
}

# fun: meta::polulate
# api: Internal
# txt: poplulate metadata values from the system
meta::populate ()
{
  meta::set "core.processors" "$(getconf _NPROCESSORS_ONLN)"
  meta::set "core.hostname" "$(hostname)"
  meta::set "core.fqdn" "$(hostname -f)"

  out::user "loaded metadata: ${#POTION_METADATA[@]} variables loaded"
}
