#! /bin/bash
# The ``mutex`` module provides a way to ensure critical region access
# across different processes. NOTE this module does not work fine on some
# filesystems, like NFS, AFS and others.

# fun: mutex::adquire <name>
# txt: create a mutex or wait until mutex removed
mutex::adquire () {
  local i=0
  tmp::create
  while ! std::mute mkdir "_mutex_$1"; do
    [ $i -eq ${MUTEX_TIMEOUT:-3600} ] && err::trace "Mutex timeout: $1"
    ${VERBOSE:-false} && out::user "waiting for mutex: $1 ($_run)"
    std::sleep 1
    ((i++))
  done
  ${VERBOSE:-false} && out::user "adquired mutex: $1 ($_run)"
}

# fun: mutex::release <name>
# txt: release mutex by name
mutex::release () {
  tmp::create
  ${VERBOSE:-false} && out::user "releasing mutex: $1 ($_run)"
  rmdir "_mutex_${1}"
}

# fun: mutex::run <name> <command> [args]
# txt: run a command protected by mutex named as argument name.
mutex::run () {
  local name="$1"; shift
  _run="$@"
  mutex::adquire "$name"
  "$@"
  local ret=$?
  mutex::release "$name"
  return $ret
}
