#! /bin/bash
# mod: secret
# txt: The `secret` module allows you to get/set passwords or secret config
#      keys from diferent sources instead of save them in plain text in the
#      potion file.

declare -A _secrets

# fun: secret::load [name=]<name>
# txt: load a secret file
secret::load () {
  local url="${1#name=}"
  case "$url" in
    gpg://*|file+gpg://*) url="${url#*://}"
      eval "$(gpg -d "$url")";;
    *) url="${url#file://}"
       # shellcheck disable=SC1090
       source "$url" || err::trace "Invalid secret file format" ;;
  esac
}

# fun: secret::add [name=]<name> content=<content>
# txt: add new secret with specified content associated with key passed as
#      argument.
secret::add () {
  eval "$(std::parse "$@")"
  # shellcheck disable=2154
  _secrets["$name"]="$content"
}

# fun: secret <name>
# txt: return the secret text associated with specified name
secret () {
  echo "${_secrets["$1"]}"
}
