#! /bin/bash
# mod: tmp
# txt: The ``tmp`` module provides functions to create and destroy temporar
#      directories.

POTION_TMPDIR="/tmp/_potion"

tmp::create () {
  mkdir -p "${POTION_TMPDIR}" && cd "${POTION_TMPDIR}"
  std::add_quit_handler tmp tmp::destroy
}

tmp::destroy () {
  cd / && rm -rf "${POTION_TMPDIR}"
}
